# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HindiSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.TextField()),
                ('song_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HindiSongAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HindiSongArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='hindisong',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrabHindiSongs.HindiSongAlbum'),
        ),
        migrations.AddField(
            model_name='hindisong',
            name='artist',
            field=models.ManyToManyField(to='GrabHindiSongs.HindiSongArtist'),
        ),
    ]
