# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanjabiSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.TextField()),
                ('song_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PanjabiSongAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.TextField()),
                ('album_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PanjabiSongArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField()),
                ('artist_type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='panjabisong',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GrabPanjabiSongs.PanjabiSongAlbum'),
        ),
        migrations.AddField(
            model_name='panjabisong',
            name='artist',
            field=models.ManyToManyField(to='GrabPanjabiSongs.PanjabiSongArtist'),
        ),
    ]
